baseURL = 'https://upemis.lt/tinklarastis'
languageCode = 'lt-LT'
defaultContentLanguage = 'lt'

[permalinks]
post = '/:slug/'
zymes = '/:slug'
autoriai = '/:slug/'

[params]
dateFormat = 'Jan 2, 2006'
homeText = 'Viskas, kas susiję su baidarėmis, upėmis, keliavimu ir aktyviu laisvalaikiu.'

[taxonomies]
tag = 'zymes'
author = 'autoriai'

[languages]
[languages.lt]
title = 'Upemis.lt tinklaraštis'
weight = 0
languageName = 'Lietuvių'

[[languages.lt.menu.main]]
name = "Maršrutai"
url = "https://upemis.lt/marsrutai"
weight = 1
[[languages.lt.menu.main]]
name = "Upės"
url = "https://upemis.lt/upes"
weight = 2
[[languages.lt.menu.main]]
name = "Tinklaraštis"
url = "/"
weight = 3

[frontmatter]
  date = ['date', 'publishDate']
  lastmod = ['lastmod', 'date']
  publishDate = ['publishDate', 'date']

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = false
